name: Lint
on:
  push:
    branches:
      - main
      - develop

jobs:
  python:
    name: Code Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.12"

      - name: Install ruff
        working-directory: ./
        run: uv add ruff

      - name: Run Ruff check
        working-directory: ./src/mlops_codex
        run: uv run ruff check --output-format=github .