name: Lint
on: pull_request

jobs:
  python:
    name: Code Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Ruff
        working-directory: ./src/mlops_codex
        run: ruff check --output-format=github .