name: Publish to PyPI

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    name: Upload release to PyPI using uv
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/datarisk-mlops-codex
    permissions:
      id-token: write  # necessário para Trusted Publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always --verbose
